// Mock data for when database connection is unavailable
export const mockTeams = [
  {
    id: 1,
    name: "Manchester United",
    league_id: 1,
    league_name: "Premier League",
    country: "England",
    logo_url: "/images/teams/manchester-united.png",
    founded_year: 1878,
    stadium: "Old Trafford",
    description: "One of the most successful clubs in English football history, with a rich tradition and global fanbase.",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: "Liverpool",
    league_id: 1,
    league_name: "Premier League",
    country: "England",
    logo_url: "/images/teams/liverpool.png",
    founded_year: 1892,
    stadium: "Anfield",
    description: "A historic club known for its passionate supporters and attacking style of play.",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: "Manchester City",
    league_id: 1,
    league_name: "Premier League",
    country: "England",
    logo_url: "/images/teams/manchester-city.png",
    founded_year: 1880,
    stadium: "Etihad Stadium",
    description: "Modern powerhouse with state-of-the-art facilities and recent domestic dominance.",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 4,
    name: "Real Madrid",
    league_id: 2,
    league_name: "La Liga",
    country: "Spain",
    logo_url: "/images/teams/real-madrid.png",
    founded_year: 1902,
    stadium: "Santiago Bernabéu",
    description: "The most successful club in European competition history with 14 Champions League titles.",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 5,
    name: "Barcelona",
    league_id: 2,
    league_name: "La Liga",
    country: "Spain",
    logo_url: "/images/teams/barcelona.png",
    founded_year: 1899,
    stadium: "Camp Nou",
    description: "Famous for its tiki-taka style and producing some of the world's greatest players.",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 6,
    name: "AC Milan",
    league_id: 3,
    league_name: "Serie A",
    country: "Italy",
    logo_url: "/images/teams/ac-milan.png",
    founded_year: 1899,
    stadium: "San Siro",
    description: "One of Italy's most successful clubs with a rich European history.",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 7,
    name: "Juventus",
    league_id: 3,
    league_name: "Serie A",
    country: "Italy",
    logo_url: "/images/teams/juventus.png",
    founded_year: 1897,
    stadium: "Allianz Stadium",
    description: "Record-holding Serie A champions with a storied legacy in Italian football.",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 8,
    name: "Bayern Munich",
    league_id: 4,
    league_name: "Bundesliga",
    country: "Germany",
    logo_url: "/images/teams/bayern-munich.png",
    founded_year: 1900,
    stadium: "Allianz Arena",
    description: "The dominant force in German football with consistent Champions League success.",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 9,
    name: "Paris Saint-Germain",
    league_id: 5,
    league_name: "Ligue 1",
    country: "France",
    logo_url: "/images/teams/psg.png",
    founded_year: 1970,
    stadium: "Parc des Princes",
    description: "French giants with significant investment and star-studded squads.",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
